spring.application.name=Ideahub

spring.datasource.url=jdbc:postgresql://localhost:5432/ideahub
spring.datasource.username=ideahub
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ai.openai.api-key=OPEN_API_KEY_HERE
#spring.ai.openai.model=gpt-3.5-turbo
spring.ai.openai.chat.options.model=gpt-3.5-turbo
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.connect-timeout=15000   # 15 seconds
spring.ai.openai.read-timeout=30000     # 30 seconds

# Async configuration
spring.task.execution.pool.core-size=5
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=25
spring.task.execution.thread-name-prefix=async-
spring.task.execution.shutdown.await-termination=true
spring.task.execution.shutdown.await-termination-period=60s
